version: "1"
name: "scalable productimage service"
services:
#  some-scylla:
#    image: scylladb/scylla:4.5.0
#    container_name: some-scylla
#    command:
#      - |
#        --seeds=some-scylla
#        --reactor-backend=epoll
#        --memory 750M
#        --smp 1
#
#  some-scylla2:
#    image: scylladb/scylla:4.5.0
#    container_name: some-scylla2
#    command:
#        - |
#          --seeds=some-scylla
#          --reactor-backend=epoll
#          --memory 750M
#          --smp 1
#    #    volumes:
##      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
##      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
##      - "./scylla/mutant-data.txt:/mutant-data.txt"
#    networks:
#      web:
#
#  some-scylla3:
#    image: scylladb/scylla:4.5.0
#    container_name: some-scylla3
#    command:
#        - |
#          --seeds=some-scylla
#          --reactor-backend=epoll
#          --memory 750M
#          --smp 1
##    volumes:
##      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
##      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
##      - "./scylla/mutant-data.txt:/mutant-data.txt"
#    networks:
#      web:
#
#networks:
#  web:
#    driver: bridge
#### SCYLLA ORIGINAL COMPOSE

#  # ScyllaDB
#  scylla-node:
#    container_name: scylla-node1
#    ports:
#      - 9043:9042
#    image: scylladb/scylla:5.2.0
#    restart: always
#    environment:
#      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
#      CASSANDRA_AUTO_BOOTSTRAP: true
#      CASSANDRA_CLUSTER_NAME: MyCluster
#      CASSANDRA_DC: DC1
#      CASSANDRA_RACK: RACK1
#      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
#      CASSANDRA_NUM_TOKENS: 128
#    #    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
#    volumes:
#      - scylla:/scylla
#    networks:
#      web:

##### SCYLLA ATTEMPT SEP

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.4.5
    restart: always
    ports:
      - 9042:9042
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --cpuset 0 --reactor-backend=epoll --overprovisioned 1 --api-address 0.0.0.0 --broadcast-rpc-address 10.0.0.4
    privileged: true
    volumes:
      - "scylla:/scylla"
    networks:
      web:

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:5.4.5
    restart: always
    ports:
      - 9043:9042
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --cpuset 0 --reactor-backend=epoll --overprovisioned 1 --api-address 0.0.0.0 --broadcast-rpc-address 10.0.0.5
    privileged: true
    volumes:
      - "scylla:/scylla"
    networks:
      web:

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:5.4.5
    restart: always
    ports:
      - 9044:9042
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --cpuset 0 --reactor-backend=epoll --overprovisioned 1 --api-address 0.0.0.0 --broadcast-rpc-address 10.0.0.6
    privileged: true
    volumes:
      - "scylla:/scylla"
    networks:
      web:

volumes:
  scylla: { }

networks:
  default:
    name: db_network
  web:
    driver: bridge