version: "1"
services:
  #  MongoDB
  mongodb-node1:
    image: mongo:6.0.2
    container_name: mongodb-node1
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongodb-node1
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/

  # ScyllaDB
  scylla-node1:
    container_name: scylla-node1
    ports:
      - 9042:9042
    image: scylladb/scylla:5.2.0
    restart: always
    environment:
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_AUTO_BOOTSTRAP: true
      CASSANDRA_CLUSTER_NAME: MyCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    #    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla:/scylla
    networks:
      web:

# Volumes & Network
volumes:
  data: { }
  scylla: { }

networks:
  default:
    name: db_network
  web:
    driver: bridge