version: "1"
services:
  # ScyllaDB
  scylla-node1:
    container_name: scylla-node1
    ports:
      - 9042:9042
    image: scylladb/scylla:5.2.0
    restart: always
    environment:
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_AUTO_BOOTSTRAP: true
      CASSANDRA_CLUSTER_NAME: MyCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    #    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - scylla:/scylla
    networks:
      web:

# Volumes & Network
volumes:
  data: { }
  scylla: { }

networks:
  default:
    name: db_network
  web:
    driver: bridge