apiVersion: apps/v1
kind: Deployment
metadata:
  name: productimage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productimage-service
  template:
    metadata:
      labels:
        app: productimage-service
    spec:
      containers:
        - name: productimage-service
          image: vandalen/kringlooptilburg-productimageservice:test
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 180
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 180
            periodSeconds: 15
          resources:
            requests:
              cpu: "400m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "768Mi"
          ports:
            - containerPort: 8083
